name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test pitfalls
      id: test-pitfalls
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: 'pip install -r requirements.txt'
        max-score: 6
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-PITFALLS_RESULTS: "${{steps.test-pitfalls.outputs.result}}"
      with:
        runners: test-pitfalls
